"""Set is_edited and is_deleted to non-nullable with default False

Revision ID: 047eaa01b4cb
Revises: d2dfbd44c3ee
Create Date: 2024-09-22 07:56:12.588256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '047eaa01b4cb'
down_revision: Union[str, None] = 'd2dfbd44c3ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Update existing NULLs to False
    op.execute(
        """
        UPDATE messages
        SET is_edited = FALSE
        WHERE is_edited IS NULL
        """
    )
    op.execute(
        """
        UPDATE messages
        SET is_deleted = FALSE
        WHERE is_deleted IS NULL
        """
    )
    
    # Step 2: Alter columns to set NOT NULL and default to False
    op.alter_column('messages', 'is_edited',
           existing_type=sa.BOOLEAN(),
           nullable=False,
           server_default='false')
    op.alter_column('messages', 'is_deleted',
           existing_type=sa.BOOLEAN(),
           nullable=False,
           server_default='false')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'is_deleted',
           existing_type=sa.BOOLEAN(),
           nullable=True,
           server_default=None)
    op.alter_column('messages', 'is_edited',
           existing_type=sa.BOOLEAN(),
           nullable=True,
           server_default=None)
    # ### end Alembic commands ###
